### ISSUE TITLE
number of items(4.82k) in Cornell-AGI/amazon_movie_tv_item_mxbai != max item indice (10533) in Cornell-AGI/amazon_movie_tv_llama_mxbai

### ISSUE THREAD

**Issue by YRYangang** [ZhaolinGao/LangPTune#1]
![image](https://github.com/user-attachments/assets/5a24ef4b-784d-4e71-831f-35c302b98987)

**Comment by ZhaolinGao** [comment]
Sorry we actually uploaded the amazon book data to amazon_movie_tv_item_mxbai. We just updated the dataset on Cornell-AGI/amazon_movie_tv_item_mxbai. Now it should contain 10533 items.
