### ISSUE TITLE
inputs(tokens) are not converted into tensors

### ISSUE THREAD

**Issue by YRYangang** [ZhaolinGao/LangPTune#2]
![image](https://github.com/user-attachments/assets/1decb8b6-e856-41ad-947c-44aeaa8fa6e6)

**Comment by YRYangang** [comment]
also, tried adding:
![image](https://github.com/user-attachments/assets/23b576ba-671b-4f64-ba45-511e60ed2ab5)

but got:

![image](https://github.com/user-attachments/assets/2b957aa9-8274-48a2-875d-025ce5abcd5e)

**Comment by ZhaolinGao** [comment]
please check if you have successfully prepared the dataset with `accelerator.prepare`.

**Comment by YRYangang** [comment]
the problem has nothing to do with `accelerator.prepare` and should be fuxed by
![image](https://github.com/user-attachments/assets/5d4d54cd-9e77-40fc-a0fe-9715241b122f)
